### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by Lebyy** [eiinet/Einet-Anake-MOFH#1]
404
HTTP 404 This page doesn't work!!

Sorry but the page you are trying to access is not available or has been deleted!!

I always get this error when trying to login/register or any action

**Comment by eiinet** [comment]
Hello I have reviewed the script again and everything works fine I remind you that if you are trying to install the script in a sub directory or folder at the end of the installation you must manually add the name of the folder in the vars.php file on the line 44 define('EA_URL', $is_ssl.$_SERVER['HTTP_HOST']);

 

it should be something like this **define('EA_URL', $is_ssl.$_SERVER['HTTP_HOST'].'/NAME_YOUR_FOLDER');**

and if you install it in the root directory you should have no problem

https://prnt.sc/v1hn3z

https://prnt.sc/v1hnb6

**Comment by Lebyy** [comment]
It was solved but may I know, how to edit the email text?

**Comment by eiinet** [comment]
to edit the text of the messages sent to the email data / php / req / req.user.php from line 75
and when a hosting account is created and the account data is sent to the user via email, it is edited in data / clases / c.panel.php from line 463

**Comment by Lebyy** [comment]
Ill close this :)
